FROM node:alpine


# Create app directory
WORKDIR /mentor_mentee_app


# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY ./package.json /mentor_mentee_app

RUN npm install
# If you are building your code for production
# RUN npm ci --omit=dev

# Bundle app source
COPY . /mentor_mentee_app/

EXPOSE 5173
CMD npm run dev -- --host